---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastly-controller.fullname" . }}
  labels:
    {{- include "fastly-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: https
    protocol: TCP
  selector:
    {{- include "fastly-controller.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastly-controller.fullname" . }}
  labels:
    {{- include "fastly-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fastly-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fastly-controller.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "fastly-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: {{ .Values.kubeRbacProxy.image.repository }}:{{ .Values.kubeRbacProxy.image.tag }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: FASTLY_API_TOKEN
          value: {{ .Values.fastly.apiToken }}
        - name: FASTLY_PLATFORM_TLS_CONFIGURATION_ID
          value: {{ .Values.fastly.tlsConfigID }}
        - name: CLUSTER_NAME
          value: {{ .Values.fastly.clusterName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}